name: Auto Scrape Highlights & Replay

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 cryptography

      - name: Run highlight scraper
        run: python scrape_highlights.py

      - name: Run replay scraper
        run: python scrape_replays.py

      - name: Push both highlight.json and replay.json to GitHub
        run: |
          git clone https://x-access-token:${{ secrets.TOKEN }}@github.com/Minkhantk269/highlight.git
          cp highlight.json replay.json highlight/
          cd highlight
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add highlight.json replay.json
          git commit -m "Auto update highlight & replay from scraper [skip ci]" || echo "No changes"
          git push

      - name: Setup SSH for DigitalOcean Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Upload highlight.json and replay.json to DigitalOcean Laravel storage folder
        run: |
          scp highlight.json replay.json ${{ secrets.DO_SERVER_USER }}@${{ secrets.DO_SERVER_IP }}:/var/www/football_live/storage/app/data/
