name: Auto Scrape Highlights & Replay

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 cryptography

      - name: Run highlight scraper
        run: python scrape_highlights.py

      - name: Run replay scraper
        run: python replay.py

      - name: Push both highlight.json and replay.json
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Minkhantk269/highlight.git
          cp highlight.json replay.json highlight/
          cd highlight
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add highlight.json replay.json
          git commit -m "Auto update highlight & replay from scraper [skip ci]" || echo "No changes"
          git push
