name: Auto Scrape Highlights

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:      # Allows manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Critical: Grants push permission
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 cryptography

      - name: Run scraper
        run: python scrape_highlights.py

      - name: Push highlight.json to another repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/Minkhantk269/highlight.git
          cp highlight.json highlight/
          cd highlight
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add highlight.json
          git commit -m "Auto update from scraper [skip ci]" || echo "No changes"
          git push


